environment: dev

port: 8080

service-name:
  binance-future: BNF
  binance-spot: BNS

secrets:
  binance-apikey: 818a296894ac07183f7595444e21b08e5b307c81e905c65fefdeeccc9ac507d5
  binance-secretKey: 4a5df610beb4ae7d3b16a87170a407c1d88611908948bb7a972e25c887f7df91

binance-future-url:
  set-leverage: /fapi/v1/leverage
  single-order: /fapi/v1/order
  miltiple-order: /fapi/v1/batchOrders
  binance-future-baseUrl:
    binance1: https://fapi.binance.com
    # binance2:
    # binance3:
    # binance4:


