environment: local

port: 8080

service-name:
  binance-future: BNF
  binance-spot: BNS
  okx-future: OKXF
  okx-spot: OKXS

secrets:
  binance-apikey:
  binance-secretKey:
  okx-apiKey:
  okx-secretKey:
  okx-passPhase:

binance-future-url:
  set-leverage: /fapi/v1/leverage
  single-order: /fapi/v1/order
  miltiple-order: /fapi/v1/batchOrders
  binance-future-baseUrl:
    binance1: https://fapi.binance.com
    # binance2:
    # binance3:
    # binance4:

okx-future-url:
  set-leverage: /api/v5/account/set-leverage
  place-position: /api/v5/trade/order
  multi-position: /api/v5/trade/batch-orders
  okx-future-baseUrl:
    okx1: https://www.okx.com

okx-spot-url:
